language: node_js
node_js:
  - "node"

cache:
  npm: true

script: npm run prerender

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: master
  on:
    branch: base
